[package]
name = "tyange-sysmon"
version = "0.1.0"
edition = "2024"

[dependencies]
chrono = "0.4.42"
dotenv = "0.15.0"
postgres = { version = "0.19.12", features = ["with-chrono-0_4"] }
sysinfo = "0.36.1"
